---
# GMT
:concurrency: 20
:queues:
  - default
  - push
  - pull
  - mailers
  - remove
  - elasticsearch
:schedule:
  subscriptions_scheduler:
    cron: '0 4,9 * * * Asia/Tokyo'
    class: Scheduler::SubscriptionsScheduler
  delete_duplicated_subscription_retry_job_scheduler:
    cron: '20 4,9 * * * Asia/Tokyo'
    class: Scheduler::DeleteDuplicatedSubscriptionRetryJobScheduler
  media_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * * Asia/Tokyo'
    class: Scheduler::MediaCleanupScheduler
  feed_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(0..2) %> * * * Asia/Tokyo'
    class: Scheduler::FeedCleanupScheduler
  doorkeeper_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(0..2) %> * * 0 Asia/Tokyo'
    class: Scheduler::DoorkeeperCleanupScheduler
  user_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(4..6) %> * * * Asia/Tokyo'
    class: Scheduler::UserCleanupScheduler
  subscriptions_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(1..3) %> * * 0 Asia/Tokyo'
    class: Scheduler::SubscriptionsCleanupScheduler
  ip_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * * Asia/Tokyo'
    class: Scheduler::IpCleanupScheduler
  email_scheduler:
    cron: '0 10 * * 2 Asia/Tokyo'
    class: Scheduler::EmailScheduler
  backup_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * * Asia/Tokyo'
    class: Scheduler::BackupCleanupScheduler
  delete_elasticsearch_documents_worker:
    cron: '*/2 * * * *'
    class: Scheduler::DeleteElasticsearchDocumentsWorker
  trend_tag_scheduler:
    cron: '*/30 * * * *'
    class: Scheduler::TrendTagScheduler
  pawoo_report_target_cleanup_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(2..4) %> * * * Asia/Tokyo'
    class: Pawoo::Scheduler::ReportTargetCleanupScheduler
  pawoo_refresh_popular_account_scheduler:
    cron: '30 3 * * 0 Asia/Tokyo'
    class: Pawoo::Scheduler::RefreshPopularAccountScheduler
  pawoo_prepare_sitemap_scheduler:
    cron: '<%= Random.rand(0..59) %> <%= Random.rand(3..5) %> * * * Asia/Tokyo'
    class: Pawoo::Scheduler::PrepareSitemapScheduler
  pawoo_report_summation_scheduler:
    cron: '10 1 * * * Asia/Tokyo'
    class: Pawoo::Scheduler::ReportSummationScheduler
